#!/bin/sh

# Originally from kdeedu/parent-adder, revision f36db9f.
# Written by Nicolás Alvarez, <nicolas.alvarez@gmail.com>

set -e

if [ -z "${RULESETDIR}" ]; then
    echo "RULESETDIR must be exported first."
    exit 1
fi

BINDIR=${RULESETDIR}/bin
PARENTMAP=${RULESETDIR}/kdeutils/ark-parentmap

# This filter-branch call does the following two things:
# 1. Adjust the parents as specified in $PARENTMAP
#    Currently, this means adjusting the parents of r694732.
# 2. Remove the directory old/
#    This is created erroneously in r694732 and needs to be removed.
git filter-branch \
    --parent-filter "$(${BINDIR}/translateRevlist.py ${PARENTMAP} | ${BINDIR}/add-parents.py)" \
    --tag-name-filter cat \
    --index-filter 'git rm --cached -r -q --ignore-unmatch old/' \
    -- --all --date-order
