#!/bin/sh

# Originally from kdeedu/parent-adder, revision f36db9f.
# Written by Nicolás Alvarez, <nicolas.alvarez@gmail.com>

set -e

if [ -z "${RULESETDIR}" ]; then
    echo "RULESETDIR must be exported first."
    exit 1
fi

BINDIR=${RULESETDIR}/bin
PARENTMAP=${RULESETDIR}/kdeutils/superkaramba-parentmap

# This filter-branch call does the following:
# 1. Adjust the parents as specified in $PARENTMAP
#    Currently, this means adjusting the parents of r456512 and r457717.
git filter-branch \
    --parent-filter "$(${BINDIR}/translateRevlist.py ${PARENTMAP} | ${BINDIR}/add-parents.py)" \
    --tag-name-filter cat \
    -- --all --date-order
