#!/bin/bash

set -e

codebefore='
merge_gitrev=;
case $GIT_COMMIT in
'
codeafter='
esac;
if [ -n "$merge_gitrev" ]; then
    echo "$(cat) -p $(map $merge_gitrev)";
else
    cat;
fi'
code="$codebefore"
while read srcrev newparent; do
    code="$code    $srcrev) newparent=$newparent;;
"
done < <(python generate-parent-map.py "$1")
code="$code$codeafter"

git filter-branch --parent-filter "$code" HEAD
