#!/bin/bash

repo=kdev-qmake # this is hardcoded in rules too!

set -e

rm -rf "$repo"
svn-all-fast-export --add-metadata --identity-map /home/gitmaster/kde-ruleset/account-map --rules rules/kdev-qmake-rules "$@" /home/gitmaster/svn/

cd "$repo"

# Synthesize merge commits, and delete vim swapfiles.
git filter-branch \
    --parent-filter "$(../rules/add-parents <(../rules/generate-parent-map.py ../rules/kdev-qmake-parent-map))" \
    --tree-filter 'rm -f qmake/duchain/.qmakeeditorintegrator.cpp.swp' \
    -- --all

# When qmakebuilder was moved into qmake/qmakebuilder, move contents of qmake into the root.
git filter-branch -f --subdirectory-filter "qmake" "$(git rev-parse ":/Move qmakebuilder into qmake plugin")^..HEAD"
