#!/bin/bash

# filter-branch script used for all kdebindings repositories
#
# - filters empty commits (--prune-empty)
# - replaces CRLF with LF via dos2unix
# - fixes "nobody@localhost" emails in cvs2svn commits

set -e

bindir="${RULESETDIR:?\$RULESETDIR must point to the kde-ruleset directory}/bin"

source "$bindir/filter-goodies"

tempdir="$(calc_tempdir kdebindings-filter)"

git filter-branch -d "$tempdir" \
--tag-name-filter cat --prune-empty \
--tree-filter '
find -type f -exec dos2unix -q "{}" "+"
find "(" -name "*.orig" -o -name "*.rej" ")" -delete
' --env-filter '
if [ "$GIT_COMMITTER_EMAIL" = "nobody@localhost" ]; then
    export GIT_COMMITTER_EMAIL=cvs2svn@kde.org
    export GIT_AUTHOR_EMAIL=cvs2svn@kde.org
    export GIT_COMMITTER_NAME="KDE Sysadmin"
    export GIT_AUTHOR_NAME="KDE Sysadmin"
fi
' -- --all
