#!/bin/bash

bindir="${RULESETDIR:?\$RULESETDIR must point to the kde-ruleset directory}/bin"

source "$bindir/filter-goodies"

tempdir="$(calc_tempdir rubyfilterbranch)"

git filter-branch --tag-name-filter cat -d "$tempdir" --tree-filter '
handle_move() {
if test -d old/$1; then
    if test -d $1; then
        rm -rf old/$1
    else
        mv old/$1 .
    fi
fi
}
handle_move qtruby
handle_move korundum
' -- --all
