#!/bin/bash

if test $# -ne 1
then
	echo Usage: test libkdegames
	exit 2
fi

module=$1

for output in $1 $1.recompressed
do
	if test -d $output
	then
		echo $output already exists, please remove it first
		exit 1
	fi
done

#export RULESETDIR=/home/wr/src/games2git/kde-ruleset

/usr/bin/git clone kde:scratch/wrohdewald/$module
cd $module
/usr/bin/git gc --aggressive
cd ..

cp -a $module $module.recompressed
cd $module.recompressed
$RULESETDIR/bin/recompress-svgz-and-png.sh
/usr/bin/git gc --aggressive
cd ..

# this is wrong, we need to do git clone file:///... from
# the recompressed repository and check the clone. Or find
# out how to remove really everything unwanted.
du -s -h $module/.git $module.recompressed/.git
